
# src/verbilo/__init__.py

try:
    # 1. Check for the file generated by your build script first
    from ._version import __version__, __build_date__
except ImportError:
    # 2. If it doesn't exist (clean repo), try to read from pyproject directly
    # This keeps your dev environment accurate without 'pip install -e'
    try:
        from pathlib import Path
        import tomllib # Python 3.11+
        
        root = Path(__file__).resolve().parents[2]
        pyproject = tomllib.loads((root / "pyproject.toml").read_text())
        __version__ = pyproject["project"]["version"]
        __build_date__ = "Development-Dynamic"
    except Exception:
        __version__ = "0.0.0-dev"
        __build_date__ = "unknown"